### ISSUE TITLE
where's the source?

### ISSUE THREAD

**Issue by vectorselector** [TelescopeJS/sample-project#12]
I notice that it's pulling sourcecode from a repo and building it but then the build target never get's any source (Heroku) just the built app. How does one go about editing a one-click-heroku-deployed telescope sample-project instance? git cloning it will only grab the build. Mind you, i can add and remove packages fine, just that it's like walking around with no pants on...

**Comment by SachaG** [comment]
Telescope's source is here: https://github.com/TelescopeJS/Telescope

You can use it for reference purpose, but you shouldn't need to edit it (refer to the documentation for more info: http://docs.telescopeapp.org)

**Comment by vectorselector** [comment]
ah ok. thanks. it's really just for the demo package and for reference
