### ISSUE TITLE
"No app-16eb2b047a18b4f36f117813970779be.json located in the repo URL provided."

### ISSUE THREAD

**Issue by timbennett** [TelescopeJS/sample-project#2]
I am logged into Heroku. When I click https://heroku.com/deploy?template=https://github.com/TelescopeJS/sample-project I get the following error in Heroku:

> No app-16eb2b047a18b4f36f117813970779be.json located in the repo URL provided.

> Make sure that an app-16eb2b047a18b4f36f117813970779be.json file exists in the project root directory.

**Comment by SachaG** [comment]
I'm getting it too. I assume it's a Heroku issue because it used to work, and also that's a weird error message.

**Comment by friism** [comment]
Are you specifying a correct root url when doing this?

**Comment by timbennett** [comment]
@friism Not sure if you're asking me, but all I'm doing is clicking the "One Click Deploy" button on http://www.telescopeapp.org.

FWIW it's now asking for app-5c96aa6a5be707f4ff05e1d8c66f0570.json instead of the one in my original comment.

**Comment by Dhaulagiri** [comment]
This was an issue on Heroku's side, but it should be fixed now.  Thanks for raising this issue!

**Comment by SachaG** [comment]
Great :)
