### ISSUE TITLE
unable to create admin account

### ISSUE THREAD

**Issue by DanFraser1** [TelescopeJS/sample-project#22]
Hi, i've deployed the sample-project on Scalingo but i'm unable to create an admin account. it seems that the register function is not working in that i can enter username/email/password but when i click register I get nothing.. I've had the same issue when I deploy on Heroku.. Can someone advise? 

https://dantesttwo.scalingo.io/

**Comment by warzi117** [comment]
I'm having the same exact issue.

**Comment by jakelevirne** [comment]
Same issue

**Comment by jakelevirne** [comment]
Oh I see... the trick is to work fromthe main repo: https://github.com/TelescopeJS/Telescope#getting-started

**Comment by SachaG** [comment]
Yes, this repo is kind of deprecated, sorry. I'll add a note about it.

**Comment by DanFraser1** [comment]
Ah yes. Thanks everyone!
