### ISSUE TITLE
Error with "meteor add my-custom-package" command

### ISSUE THREAD

**Issue by TaiMino** [TelescopeJS/sample-project#3]
I get this error below when I run "meteor add my-custom-package" command.

----------------------------------------------------------
 => Errors while parsing arguments:

While adding package my-custom-package:
error: no such package

**Comment by SachaG** [comment]
Not sure what's going on, I just tested it and it works for me?

**Comment by TaiMino** [comment]
I still am not sure what the problem is.  Do you know any other ways to implement this?

**Comment by SachaG** [comment]
I can't really help you without more details (what you did, link to your code…), sorry.

**Comment by TaiMino** [comment]
Thank you anyway.  I actually should have asked this question on stackoverflow.  I will close this issue.
